### ISSUE TITLE
Mika, hello!

### ISSUE THREAD

**Issue by ol4ikwas** [CELLgainz/Cellframe#2]
How are you? What's happened? Please give us know you are ok. We are very worried about you. 
Olga

**Comment by hyttmi** [comment]
> How are you? What's happened? Please give us know you are ok. We are very worried about you. Olga

Got some bad news and needed a break. I will return on some point.

**Comment by ol4ikwas** [comment]
Got you. Thank you for your responce. I'm very sorry to hear it, please accept my deepest condolences for you. Take your time and return when you will be ready. You're always welcome. I'm glad to know you're okay (in some way).

**Comment by hyttmi** [comment]
.
